# global env
[ -f $HOME/.env ] && source $HOME/.env
[ -f $HOME/.alias ] && source $HOME/.alias

# oh-my-zsh env
export LANG=en_US.UTF-8
export ZSH=$HOME/.oh-my-zsh

# http://leetschau.github.io/remove-duplicate-zsh-history.html
# for fzf
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

unsetopt SHARE_HISTORY
unsetopt INC_APPEND_HISTORY

ZSH_THEME="ys"

plugins=(git z golang python virtualenvwrapper kubectl docker)

# For AWS
AWS_VAULT_BACKEND=secret-service
export AWS_VAULT_BACKEND

# For fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# setup oh-my-zsh
source $ZSH/oh-my-zsh.sh
