# Path to your oh-my-zsh installation.
export LANG=en_US.UTF-8
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"

plugins=(git z golang python virtualenvwrapper pipenv kubectl)

# alias
alias tmux="TERM=screen-256color-bce tmux"

# Local bin path config
source $ZSH/oh-my-zsh.sh
export LOCALBIN=$HOME/bin
export PATH="$LOCALBIN:$PATH"

# Golang
export GOPATH=$HOME/projects/go
export GOROOT=$LOCALBIN/go
export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"

# NodeJS
export NODEJSPATH=$LOCALBIN/node/bin
export PATH="$NODEJSPATH:$PATH"

# Clang
export CLANGPATH=$LOCALBIN/clang/bin
export PATH="$CLANGPATH:$PATH"

# Java
export JAVA_HOME=$LOCALBIN/jdk
export JRE_HOME=$LOCALBIN/jdk/jre
export MAVEN_HOME=$LOCALBIN/maven
export SPRING_HOME=$LOCALBIN/spring
export PATH="$JAVA_HOME/bin:$MAVEN_HOME/bin:$SPRING_HOME/bin:$PATH"

# Rust
export CARGO_HOME=$LOCALBIN/cargo/
export PATH="$CARGO_HOME/bin:$PATH"
# protoc
export PROTOC_BIN=$LOCALBIN/protoc/bin
export PATH="$PROTOC_BIN:$PATH"

# SNAP bin
export PATH="/snap/bin:$PATH"

# Python virtualenvwrapper
export WORKON_HOME=$LOCALBIN/virtualenv
source /usr/local/bin/virtualenvwrapper.sh

# k8s
source <(kubectl completion zsh)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
